image: node:8

before_script:  
  - git config --global user.email "gitlab-ci@minidigger.me"
  - git config --global user.name "Gitlab-CI@MiniDigger"

cache:  
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

promote-patch:
  stage: deploy
  script:
    - npm version patch  
    - git push --follow-tags    
  when: manual

promote-minor:
  stage: deploy
  script:
    - npm version minor  
    - git push --follow-tags  
  when: manual  
    
promote-major:
  stage: deploy
  script:
    - npm version major  
    - git push --follow-tags  
  when: manual

publish:  
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish